package se.lexicon.ecommerce.model.entity;


import jakarta.persistence.*;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

// Mark this class as DB managed object (entity)
@Entity
// Define specific name of DB table
@Table(name = "addresses")
// Lombok: Automatically generate getters, setters, toString etc
@Data
// Lombok: Create constructor with no arguments
@NoArgsConstructor
// Lombok: Create a constructor with all fields as arguments
@AllArgsConstructor
public class Address {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    // Unique ID for each address, auto-generated by DB
    private Long id;

    // The street address, can't be empty in DB
    @Column(nullable = false)
    private String street;

    // City name - can't be empty in DB
    @Column(nullable = false)
    private String city;

    // Postal code, can't be empty and limited to 20 characters
    @Column(nullable = false, length = 20)
    private String zipCode;

    // Fields will go here


}